### ISSUE TITLE
Support for Ergo ProSmart Base

### ISSUE THREAD

**Issue by EnragedMagician** [richardhopton/smartbed-mqtt#10]
I have the latest Ergo ProSmart base and I am using smartbed-mqtt in Home Assistant 2023.7.3. The base model shows as STS60 ~which I don't think is accurate~ and I don't have access to any of the environmental sensors in the base. Some other entities don't work like the left and right sensor status, info, and device info.

Please let me know if there's anything I can do to help bring full support for the ProSmart base into smartbed-mqtt. Thanks!

**Comment by EnragedMagician** [comment]
Ok so the model is correct, here is the information on my base from the Sleeptracker app:

Version: H-2.1.0 Build 87R
Model: STS-60
Firmware: 6.1.25

**Comment by richardhopton** [comment]
Can you send screenshots of the entities created from the bed device?

**Comment by richardhopton** [comment]
PS. The environmental sensors don't seem to be exposed by the Sleeptracker API for STS-60 models... I will likely be removing them in a future release since they are also very inaccurate.

**Comment by EnragedMagician** [comment]
<img width="2085" alt="Screenshot 2023-07-24 at 9 55 38 AM" src="https://github.com/richardhopton/smartbed-mqtt/assets/46495224/0dcd29f9-3a4f-40fa-9dfb-409820dc7840">
<img width="2085" alt="Screenshot 2023-07-24 at 9 55 55 AM" src="https://github.com/richardhopton/smartbed-mqtt/assets/46495224/a4908449-711b-4a14-8135-fbc7324bd721">

**Comment by EnragedMagician** [comment]
I was able to pull the following environmental data for my sensors via Postman:

`{
    "statusCode": 0,
    "statusMessage": "",
    "id": "TEST_ANDROID_environmentalData",
    "degreesCelsius": {
        "status": "valid",
        "lastUpdatedGMTSecs": 1690215063,
        "value": 21.535308837890625,
        "accuracy": null
    },
    "humidityPercentage": {
        "status": "valid",
        "lastUpdatedGMTSecs": 1690215063,
        "value": 45.05962371826172,
        "accuracy": null
    },
    "co2Ppm": {
        "status": "valid",
        "lastUpdatedGMTSecs": 1690215063,
        "value": 509.4612121582031,
        "accuracy": null
    },
    "vocPpb": {
        "status": "valid",
        "lastUpdatedGMTSecs": 1690215063,
        "value": 518.200933933258,
        "accuracy": null
    },
    "iaq": null
}`

**Comment by EnragedMagician** [comment]
I found that the hello API command provided direct access to the BME680 sensor data (which includes more sensor data than the latestEnvironmentSensorData API) so I just used a RESTful sensor to pull the environmental sensor data and I found it to be pretty accurate. Of course sensor drift is inevitable and calibration is likely needed on an ongoing basis but overall I'm pretty satisfied:

<img width="501" alt="Screenshot 2023-07-29 at 11 05 01 AM" src="https://github.com/richardhopton/smartbed-mqtt/assets/46495224/b637c58f-9fe3-4567-9064-f8504954da48">

**Comment by xodlike** [comment]
@richardhopton @EnragedMagician Any guidance for how to get the environmental data into HASS w/ an STS-60?

**Comment by richardhopton** [comment]
@xodlike @EnragedMagician I'm very concerned that FullPower will start locking out users who call this very large API too frequently, which is why I only call it once. I'd recommend getting a native solution that can support this data capture without the risks associated with calling their API too frequently.

**Comment by richardhopton** [comment]
Closing as won't do

**Comment by carlosgamezvillegas** [comment]
@EnragedMagician,

Can you share how you were able to pull out environmental information and build the dashboard you shared on Jul 29?

Thank you,
