### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by elylv** [richardhopton/smartbed-mqtt#15]
I am getting errors when starting:
error [2023-11-15T05:43:45.530Z] Error: PostRequest.postRequest: HTTP error: HttpStatusLine: caller: PostRequest.postRequest statusCode: 503 reasonPhrase: Service Unavailable protocolName: UNDEFINED protocolVersion: 1.1
error [2023-11-15T05:43:45.530Z] [Sleeptracker] Could not load helloData

I guess their API has changed?

**Comment by richardhopton** [comment]
@elylv looks like bad credentials, but as @ColoradoBills mentioned, pls join the Discord and we can try to help.
