### ISSUE TITLE
Create sensor for sleep and awake

### ISSUE THREAD

**Issue by thecheatah** [richardhopton/smartbed-mqtt#2]
Not sure if the apps can see if you are sleeping or not, but it would be nice to have a sensor if you are sleeping or not.

**Comment by richardhopton** [comment]
Sadly the apps don't know in realtime if you are asleep or awake... I could potentially download and ingest the sleep summary on demand, but presence detection just isn't an option I'm afraid.

**Comment by thecheatah** [comment]
![8C2ABCCE-75BD-45CC-89B3-29326DE16455](https://user-images.githubusercontent.com/609629/221360554-f957384b-63c1-42b8-8f24-0064c68cead6.png)

when I open the app I see this screen. It doesn’t seem to be immediate, but would be a good input for a sensor.

Really appreciate the work and how easy it was to install!

**Comment by richardhopton** [comment]
Hmm - I've never seen this screen before. I guess I wake up after my wife all the time, and tend to check my sleep hours later. I'll look to see if I can figure out how that is working... reverse engineering this "api" has not been straightforward.

**Comment by richardhopton** [comment]
Okay - this doesn't really work how you think it does... Unless you manually start a recording the app doesn't know until you wake up... then it waits at least an hour then processes the data. I set this up to query every minute and the sleeptracker API return no "current recording" until I woke up.

I woke up at 6:22.
<img width="488" alt="Screenshot 2023-02-27 at 12 13 00 PM" src="https://user-images.githubusercontent.com/1157451/221674545-25a76726-2d62-482c-ae3e-b0dcf20fb193.png">

**Comment by thecheatah** [comment]
What does the purple mean? I wonder if the state going into purple would indicate that there is wake up activity happening. I understand it won't be precise.

**Comment by richardhopton** [comment]
The blue color is "Not Recording", purple is "Auto Pending" - my point was that I went to bed at around 1am, and nothing changed on the API until it thought I might be awake... Looks like the processor doesn't send anything up to the cloud, so I can't get anything useful out.

**Comment by richardhopton** [comment]
GIven these findings, short of you manually starting and stopping the recording, this would not be valuable.
