### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by reicharb** [richardhopton/smartbed-mqtt#26]
Trying to set up sleeptracker type beauryrest and keep getting this error.  I don't have antisnore on a sleep tracker. Any ideas?

Using discovered MQTT Host: core-mosquitto
Using discovered MQTT Port: 1883
Using discovered MQTT User: addons
Using discovered MQTT password: <hidden>
info [2024-03-20T10:43:22.952Z] [MQTT] Connecting...
info [2024-03-20T10:43:23.063Z] [MQTT] Connected
error [2024-03-20T10:43:24.942Z] TypeError: Cannot read properties of null (reading 'antiSnorePresetSupported')
error [2024-03-20T10:43:24.943Z] Exit code: 2
warn [2024-03-20T10:43:24.944Z] Shutting down Smartbed-MQTT...

Edit:
Now that I a looking I don"t have a sleeptracker AI controlled bed.  I just have a speepstracker that came with my Beautyrest

**Comment by richardhopton** [comment]
Perhaps you can join the discord so I can ask you about your sleeptracker.

**Comment by edave** [comment]
Hello, I'm encountering the same problem with a Sleeptracker STS-20 (which is branded as Beautyrest). 

If I use `type: beautyrest` I get this error:
```
No Home Assistant MQTT service found, using defaults
Using default MQTT Host: 172.30.32.1
Using default MQTT Port: 1883
info [2025-09-25T05:02:36.079Z] [MQTT] Connecting...
info [2025-09-25T05:02:36.149Z] [MQTT] Connected
error [2025-09-25T05:02:37.365Z] TypeError: Cannot read properties of null (reading 'antiSnorePresetSupported')
error [2025-09-25T05:02:37.366Z] Exit code: 2
warn [2025-09-25T05:02:37.366Z] Shutting down Smartbed-MQTT...
```

If instead use `type: tempur` I get an axios error instead:
```
No Home Assistant MQTT service found, using defaults
Using default MQTT Host: 172.30.32.1
Using default MQTT Port: 1883
info [2025-09-25T05:02:49.076Z] [MQTT] Connecting...
info [2025-09-25T05:02:49.146Z] [MQTT] Connected
error [2025-09-25T05:02:49.432Z] AxiosError: Request failed with status code 401
error [2025-09-25T05:02:49.432Z] [Sleeptracker] Could not load devices
```

I also tried the most recent branch `release_1.1.23` and the axios bump (`dependabot/npm_and_yarn/axios-1.12.0`), but ran into the same problems.
