### ISSUE TITLE
How to get richmat remote id?

### ISSUE THREAD

**Issue by deadrubberboy** [richardhopton/smartbed-mqtt#32]
Hello! 

Thank you for this project! I have a Casper split king frame with 2 Richmat remotes. I believe them to be bluetooth based on the FCC site searched from numbers on back of remote.

I have ESP32 board setup as BT Proxy. Have Smarted-MQTT installed. It connects to MQTT, and to the IP of the ESP32 and says searching for "the placeholder Richmat device12345" in config example. 

How do I "capture" the bluetooth signal or whatever info I need to enter there? Not sure what/where the remote info is. I have 2 remotes, so I understand I'll need 2 ESP32 boards. I have them, just starting with 1 (my side) because I'm not foolish enough to mess with my wife's side until I test it out thoroughly. lol

Thank you! My first ESP32 project.

**Comment by richardhopton** [comment]
You shouldn't need two ESP32s as they can connect to up to three devices. It won't hurt to have two, but it's not totally necessary.

As for getting the BT name, you can use apps like ble hero or nrf connect to survey the BLE devices around you.

If you need more assistance please jump on the Discord as there are many other users who would be happy to help you.
