### ISSUE TITLE
Errors after massage step command

### ISSUE THREAD

**Issue by jeffreyrdubois** [richardhopton/smartbed-mqtt#33]
I have had this issue since the beginning, not sure if this just me. But when I use the "massage head step" button, it works, the vibrate starts, but from then on everything is broken until I restart the add-on and unplug, and replug the bed. Here are the errors I am getting:

`[Sleeptracker] {"statusCode":28,"statusMessage":"Exception while building this status object. EX (string): 'Fetch status I/O with controller failed'","id":"TEST_ANDROID_adjustableBaseControls","body":{"statusCode":-4,"statusMessage":"Exception while building this status object. EX (string): 'Fetch status I/O with controller failed'","connectionStatus":"undefined","snapshots":[],"invariants":[]}}
info [2024-06-05T03:14:53.946Z] [Sleeptracker] Fetching data for bed 351152
error [2024-06-05T03:15:01.083Z] [Sleeptracker] {"statusCode":1,"statusMessage":"Error sending message to Motor Task","id":"TEST_ANDROID_adjustableBaseControls","body":{"statusCode":-26,"statusMessage":"Error sending message to Motor Task","connectionStatus":null,"snapshots":[],"invariants":[]}}
error [2024-06-05T03:15:11.296Z] [Sleeptracker] {"statusCode":1,"statusMessage":"Error sending message to Motor Task","id":"TEST_ANDROID_adjustableBaseControls","body":{"statusCode":-26,"statusMessage":"Error sending message to Motor Task","connectionStatus":null,"snapshots":[],"invariants":[]}}`

**Comment by richardhopton** [comment]
I've seen this even when using the BT dongles or local-control prototype. It looked like the vibration caused a bunch of interference and stopped the bed controller from receiving commands.

Perhaps you could jump on the discord and share some more details about the bed/sleeptracker version.
