### ISSUE TITLE
Integration possibilities for Tempurpedic with Okin controller cu358-2?

### ISSUE THREAD

**Issue by rct** [richardhopton/smartbed-mqtt#36]
I'm looking for possible ways to integrate my Tempurpedic adjustable frame from 2019. AFAICT it doesn't have WIFI or Bluetooth. 

The frame has a control box from Okin,, CU358-2, JLDP.15.001.016. The following is what I've been able to piece together so far, maybe someone can put me on the right track, or maybe this will help someone else.  I might also post this on the Home Assistant forum.

I believe the same control system has been used on a number of other manufacturer's (Serta) frames, so this control system might be known by other names.  The FCC report mentions Jiaxing Shufude Electric Bed Co.  I found this repo because of the reference "[Leggett & Platt](https://github.com/richardhopton/smartbed-mqtt#leggett--platt-support-ble) (Okin & Richmat variants) [prototype]"

There is an RF remote in the 2.4Ghz range but I haven't seen any clues, other than the frequency range (2.403-2.48 GHz)  to make me think it is Bluetooth/BLE. FCC ID: [WKZRF358A](https://fccid.io/WKZRF358A). The remote, RF358A, does get paired with the control unit, but I've never recognized any bluetooth advertisements as possibly from the adjustable frame controller. There is a serial number printed on the remote and control unit, but nothing looking like MAC addresses. 

There is a 5 pin round DIN connection. labeled multifunction that accessories like lights and the box that synchronizes two frames connects to. So guessing it is some sort of bus or multidrop connection (RS-485?).  The frame control system seems to run on 29Vdc. So there is 29Vdc on one of the pins of the 5 pin connector. 

I found an Australian site that has what looks like a bluetooth add-on box that plugs into the 5 pin DIN bus, but there is very little info available. It does claim that the Okin app can then be used to control the frame via Bluetooth. I was able to find some more details in this FCC test report: https://fccid.io/WKZBT40SA.   There are some of those bluetooth boxes available on Ebay. (one seller looks above board, another has a 33% approval rating).

Anyone have any sort of solution or clues?

**Comment by richardhopton** [comment]
Feel free to join the discord - I'm working on a local control box that uses ESPHome to connect directly into the 5-pin DIN plug.

**Comment by rct** [comment]
Thanks. I don't spend too much time hanging out on discord. I'll try to check in every now and then but I hope you announce your progress other places so it gets noticed.
