### ISSUE TITLE
Updates Stop after Home Assistant Update

### ISSUE THREAD

**Issue by thecheatah** [richardhopton/smartbed-mqtt#7]
After an HA update, the data for the bed goes into Unavailable status. No errors show up in the logs.

If I was to guess, the MQTT connection needs a retry mechanism.

Edit: I tried restarting MQTT manually. It reconnected correctly.

**Comment by richardhopton** [comment]
Looks like when HA restarts it needs a replay of the publish messages, is MQTT restarts and HA doesn't then the existing retry mechanism is sufficient.

**Comment by richardhopton** [comment]
Check out 1.0.6
